version: 2.1
jobs:
    configure_infrastructure:
        docker: 
            - image: python:3.7-alpine3.11

        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: ["32:4d:04:cc:69:1d:23:c5:0f:0d:b7:fb:25:a0:3e:5f", "6f:7f:c4:6c:55:99:17:2a:cc:e9:bb:83:4f:0f:7d:11"]

            - run:
                name: Install Dependencies
                command: |
                    apk add --update ansible
                
            - run:
                name: Configure server
                command: |
                    ansible-playbook main-remote.yml -i inventory
workflows:
    my_work_flow:
        jobs:
            - configure_infrastructure