version: 2.1
jobs:
    configure_infrastructure:
        docker: 
            - image: python:3.7-alpine3.11

        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: 
                    - "c4:e8:d3:26:b3:4a:a8:ae:06:90:35:9e:8e:c5:37:10"
            - run:
                name: Install Dependencies
                command: |
                    apk add --update ansible
                
            - run:
                name: Configure server
                command: |
                    ansible-playbook main-remote.yml -i inventory
workflows:
    my_work_flow:
        jobs:
            - configure_infrastructure