version: 2.1
jobs:
    configure_infrastructure:
        docker: 
            - image: python:3.7-alpine3.11

        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: 
                    - "6f:7f:c4:6c:55:99:17:2a:cc:e9:bb:83:4f:0f:7d:11"
            - run:
                name: Install Dependencies
                command: |
                    apk add --update ansible
                
            - run:
                name: Configure server
                command: |
                    ansible-playbook -i inventory main-remote.yml
workflows:
    my_work_flow:
        jobs:
            - configure_infrastructure